# Файл базы данных.
database: 'database.db'
# Включен ли автоподбор автоматически?
autoPickupActivated: false

# Блоки, которые будут игнорировать правила плагина.
# Список всех блоков: https://jd.papermc.io/paper/1.20.4/org/bukkit/Material.html
whitelistBlocks:
  - GRASS_BLOCK
  - STONE

messages:
  noPerm: '<red>Недостаточно прав.'
  onlyPlayers: '<red>Доступно только игрокам.'
  reloaded: '<green>Конфиги перезагружены.'
  toggledOn: '<yellow>Автоподбор <green>включен.'
  toggledOff: '<yellow>Автоподбор <red>выключен.'